default_platform(:ios)

platform :ios do
  desc "Run unit and UI tests"
  lane :tests do
    run_tests(
      project: "ObServe.xcodeproj",
      scheme: "ObServe",
      devices: ["iPhone 16"],
      clean: true
    )
  end

  desc "Build and upload to TestFlight"
  lane :beta do
    setup_ci if is_ci

    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_content: ENV["ASC_PRIVATE_KEY"],
      is_key_content_base64: true
    )

    sync_code_signing(
      type: "appstore",
      api_key: api_key,
      readonly: true
    )

    increment_build_number(xcodeproj: "ObServe.xcodeproj")

    build_app(
      project: "ObServe.xcodeproj",
      scheme: "ObServe",
      export_method: "app-store"
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end

  desc "Build and submit to App Store"
  lane :release do
    increment_build_number(xcodeproj: "ObServe.xcodeproj")
    build_app(
      project: "ObServe.xcodeproj",
      scheme: "ObServe",
      export_method: "app-store",
      xcargs: "CODE_SIGN_STYLE=Automatic"
    )
    upload_to_app_store(
      submit_for_review: true,
      automatic_release: false,
      skip_screenshots: true,
      skip_metadata: true
    )
  end
end
